### ISSUE TITLE
socket stream has expired node-red

### ISSUE THREAD

**Issue by jonaseymour** [izevaka/powersensor-home-assistant#4]
Hi. Thanks for your work on this integration. I've got a new powersensor, and it's great to be able to get the data into home assistant.
I set this all up the other day, and it was working perfectly, but stopped reporting data after about a day and it appears the culprit was a node-red socket subscription warning, and then expiry. So it was no longer sending anything to mqtt broker.

Apologies if this is not the place to post this (I tried googling fixes for the error to no avail). This is my first flow in node-red, so I'm not sure if there was something extra I needed to set up in node-red to have it continue to listen to and send packets?
Is this to do with the chattiness of the plug/sensors sending so many messages?

I tried restarting node-red and nothing is being sent anymore (nothing in logs other than start-up procedure).

**Comment by jonaseymour** [comment]
Sorry, IP address of plug went and changed on me for some reason even though I had reserved one for it on router.

**Comment by izevaka** [comment]
Oh good one. That was going to be my first question - has the IP address changed and whether or not the plug is still visible in the PowerSensor app.

**Comment by jonaseymour** [comment]
Yep. All good now. And all working with [tesla style card](https://github.com/reptilex/tesla-style-solar-power-card)
![image](https://user-images.githubusercontent.com/7194997/180890852-81c6e3c0-ec68-4727-8740-2e6ab50bb6b9.png)

Thanks for your work on this!
