### ISSUE TITLE
Export power

### ISSUE THREAD

**Issue by drc38** [izevaka/powersensor-home-assistant#5]
I've just installed solar and unfortunately I am not getting any negative readings from the UDP packets.

@izevaka any ideas on how the official App shows negative export power when solar is exporting yet the `power` and `summation` reported through UDP packets are both positive?!

**Comment by drc38** [comment]
Note my sensor only reports back in units of `U` 
I have also noticed the UDP messages lag what is displayed on the App, again odd as you would expect the local interface to present more accurate data than through the cloud-based App.

**Comment by izevaka** [comment]
Can you a raw dump of the sensors for me? I suspect that they simply report the absolute value and the app knows to invert the solar one. Although according to #6 it seems that the values in the UDP stream are negative.

```
$> echo -n 'subscribe(30)\n' | nc -u IP_ADDRESS_PLUG 49476 | grep '"device":"sensor"'
```

**Comment by drc38** [comment]
Thanks, got it sorted with help from the powersensor team. It turns out the sensor was not connecting to the wifi. Once it did then it started reporting W with the correct sign. Not sure why the U value does not though.

**Comment by izevaka** [comment]
Oh nice one, thanks for letting me know. Closing this one :)
